root: ./
​structure:
  readme: README.md
  summary: SUMMARY.md​
redirects:
  ai-assistant: get-started/airstack-ai.md
  use-cases/universal-resolver: guides/resolve-identities.md
  use-cases/farcaster: guides/farcaster/README.md
  use-cases/farcaster/universal-resolver: guides/resolve-identities/farcaster.md
  use-cases/poaps: guides/poap/README.md
  reference/api-reference/socials-api: api-references/api-reference/socials-api/README.md
  reference/api-reference/socials-api/socials-api-examples: api-references/api-reference/socials-api/socials-api-examples.md
  reference/api-reference/poaps-api: api-references/api-reference/poaps-api/README.md
  reference/api-reference/poaps-api/poaps-api-examples: api-references/api-reference/poaps-api/poaps-api-examples.md
  reference/api-reference/domains-api: api-references/api-reference/domains-api/README.md
  reference/api-reference/domains-api/domains-api-examples: api-references/api-reference/domains-api/domains-api-examples.md
  reference/api-reference/wallet-apis: api-references/api-reference/wallet-api/README.md
  reference/api-reference/wallet-apis/wallet-api-examples: api-references/api-reference/wallet-api/wallet-api-examples.md
  reference/api-reference/poapevents-api: api-references/api-reference/poapevents-api/README.md
  reference/api-reference/poapevents-api/poapevent-api-examples: api-references/api-reference/poapevents-api/poapevent-api-examples.md
  reference/api-reference/marketplacestats-api: api-references/api-reference/marketplacestats-api.md
  reference/api-reference/airstack-identity-api: api-references/api-reference/airstack-identity-api.md
  reference/api-reference/cross-chain-queries: api-references/api-reference/cross-chain-queries.md
  reference/api-reference: api-references/api-reference/README.md
  reference/api-reference/collectionstats-api: api-references/api-reference/collectionstats-api.md
  reference/api-reference/nftstats-api: api-references/api-reference/nftstats-api.md
  reference/api-reference/nftsaletransactions-api: api-references/api-reference/nftsaletransactions-api/README.md
  reference/api-reference/nftsaletransactions-api/nftsaletransactions-api-examples: api-references/api-reference/nftsaletransactions-api/nftsaletransactions-api-examples.md
  reference/working-with-graphql: api-references/working-with-graphql.md
  guides/contact-recommendation: guides/recommend-users/README.md
  guides/contact-recommendation/social-follows: guides/recommend-users/social-follows.md
  guides/recommendation-engine/social-follows: guides/recommend-users/social-follows.md
  guides/recommendation-engine: guides/recommend-users/README.md
  guides/farcaster/recommendation-engines: guides/farcaster/recommend-users.md
  readme: README.md
  readme-1: README.md
  get-started/pricing: pricing.md
  get-started/api-status-and-roadmap: readme/api-capabilities.md
  readme/use-cases: guides/onchain-graph.md
  pricing: README.md
  api-references/api-reference/domains-api/domains-api-examples: guides/ens-domains/README.md
  api-references/api-reference/wallet-api/wallet-api-examples: guides/wallet.md
  guides/farcaster/onchain-kit-for-farcaster-frames: farcaster/farcaster-frames/airstack-frames-sdk/onchain-kit.md
  guides/airstack-frog-recipes-and-middleware: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/README.md
  guides/airstack-frog-recipes-and-middleware/onchain-data: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/onchain-data.md
  guides/airstack-frog-recipes-and-middleware/farcaster-hubs: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/farcaster-hubs.md
  guides/airstack-frog-recipes-and-middleware/allow-list: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/allow-list.md
  guides/airstack-frog-recipes-and-middleware/captcha-verification: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/captcha-verification.md
  guides/airstack-frog-recipes-and-middleware/airstack-frog-middleware: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/airstack-frog-middleware.md
  guides/farcaster-frames: farcaster/farcaster-frames/README.md
  guides/airstack-frog-recipes-and-middleware/integrate-to-existing-frog-project: frames/integrations/frog.md
  guides/airstack-frog-recipes-and-middleware/quickstart: frames/quickstart/README.md
  guides/airstack-frog-recipes-and-middleware/quickstart/node.js: frames/quickstart/node.js.md
  frames/farcaster-frames: farcaster/farcaster-frames/README.md
  frames/quickstart: farcaster/farcaster-frames/quickstart/README.md
  frames/quickstart/node.js: farcaster/farcaster-frames/quickstart/node.js.md
  frames/quickstart/next.js: farcaster/farcaster-frames/quickstart/next.js.md
  frames/airstack-frog-recipes-and-middleware: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/README.md
  frames/airstack-frog-recipes-and-middleware/onchain-data: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/onchain-data.md
  frames/airstack-frog-recipes-and-middleware/farcaster-hubs: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/farcaster-hubs.md
  frames/airstack-frog-recipes-and-middleware/allow-list: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/allow-list.md
  frames/airstack-frog-recipes-and-middleware/captcha-verification: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/captcha-verification.md
  frames/airstack-frog-recipes-and-middleware/airstack-frog-middleware: farcaster/farcaster-frames/airstack-frog-recipes-and-middleware/airstack-frog-middleware.md
  frames/airstack-frames-sdk: farcaster/farcaster-frames/airstack-frames-sdk/README.md
  frames/airstack-frames-sdk/onchain-kit: farcaster/farcaster-frames/airstack-frames-sdk/onchain-kit.md
  frames/airstack-frames-sdk/allow-list: farcaster/farcaster-frames/airstack-frames-sdk/allow-list.md
  frames/airstack-frames-sdk/captcha-verification: farcaster/farcaster-frames/airstack-frames-sdk/captcha-verification.md
  frames/airstack-frames-sdk/airstack-frog-middleware: farcaster/farcaster-frames/airstack-frames-sdk/airstack-frog-middleware.md
  frames/airstack-framesjs-middleware: farcaster/farcaster-frames/airstack-framesjs-middleware/README.md
  frames/airstack-framesjs-middleware/onchain-data: farcaster/farcaster-frames/airstack-framesjs-middleware/onchain-data.md
  frames/airstack-framesjs-middleware/allow-list: farcaster/farcaster-frames/airstack-framesjs-middleware/allow-list.md
  frames/integrations: farcaster/farcaster-frames/integrations/README.md
  frames/integrations/frog: farcaster/farcaster-frames/integrations/frog.md
  cast-actions/quickstart: farcaster/cast-actions/quickstart.md
  guides/farcaster: farcaster/farcaster/README.md
  guides/farcaster/airstack-onchain-kit-for-farcaster-frames: farcaster/farcaster/airstack-onchain-kit-for-farcaster-frames.md
  guides/farcaster/allow-lists-for-farcaster-frames: farcaster/farcaster-frames/airstack-frames-sdk/allow-list.md
  guides/farcaster/frames-validator: farcaster/farcaster-frames/frames-validator.md
  guides/farcaster/trending-mints: farcaster/farcaster/trending-mints.md
  guides/farcaster/activate-kit-for-farcaster-auth-kit: farcaster/farcaster/activate-kit-for-farcaster-auth-kit.md
  guides/farcaster/farcaster-frames: farcaster/farcaster-frames.md
  guides/farcaster/farcaster-casts: farcaster/farcaster-casts.md
  guides/farcaster/farcaster-channels: farcaster/farcaster-channels.md
  guides/farcaster/get-token-balances: farcaster/farcaster/get-token-balances.md
  guides/farcaster/resolve-farcaster-users: farcaster/farcaster/resolve-farcaster-users.md
  guides/farcaster/search-farcaster-users: farcaster/farcaster/search-farcaster-users.md
  guides/farcaster/farcaster-users-details: farcaster/farcaster/farcaster-users-details.md
  guides/farcaster/farcaster-profile-image: farcaster/farcaster/farcaster-profile-image.md
  guides/farcaster/farcaster-followers: farcaster/farcaster/farcaster-followers.md
  guides/farcaster/farcaster-following: farcaster/farcaster/farcaster-following.md
  guides/farcaster/follows-in-common: farcaster/farcaster/follows-in-common.md
  guides/farcaster/farcaster-power-badge: farcaster/farcaster/farcaster-power-badge.md
  guides/farcaster/token-holders: farcaster/farcaster/token-holders.md
  guides/farcaster/tokenbound-erc6551-accounts: farcaster/farcaster/tokenbound-erc6551-accounts.md
  guides/farcaster/token-gating: farcaster/farcaster/token-gating.md
  guides/farcaster/tokens-in-common: farcaster/farcaster/tokens-in-common.md
  guides/farcaster/recommendation-users: farcaster/farcaster/recommendation-users.md
  guides/no-code-frames: farcaster/no-code-frames/README.md
  guides/no-code-frames/token-balances: farcaster/no-code-frames/token-balances.md
  guides/no-code-frames/token-holders: farcaster/no-code-frames/token-holders.md
  guides/trending-swaps: abstractions/trending-swaps.md
  guides/trending-tokens: abstractions/trending-tokens/README.md
  guides/trending-tokens/all-base-users: abstractions/trending-tokens/all-base-users.md
  guides/trending-tokens/farcaster-users: abstractions/trending-tokens/farcaster-users.md
  guides/trending-mints: abstractions/trending-mints/README.md
  guides/trending-mints/global: abstractions/trending-mints/global.md
  guides/trending-mints/farcaster-users: abstractions/trending-mints/farcaster-users.md
  guides/trending-mints/onchain-graph: abstractions/trending-mints/onchain-graph.md
  guides/trending-mints/common-minters: abstractions/trending-mints/common-minters.md
  guides/farcaster/proof-of-personhood-for-farcaster-frames: farcaster/farcaster-frames/airstack-frames-sdk/allow-list.md
  guides/basics: basics/README.md
  guides/overview: README.md
  guides/basics/variables: basics/variables.md
  guides/basics/pagination-in-airstack-sdk: basics/pagination-in-airstack-sdk.md
  guides/basics/limit: basics/limit.md
  guides/basics/multiple-queries-execution: basics/multiple-queries-execution.md
  guides/basics/generate-typescript-interfaces: basics/generate-typescript-interfaces.md
  get-started/get-api-key: get-api-key.md
  get-started/quickstart: quickstart.md
